api_platform:
    title: 'Symfony REST API de tournoi'
    description: 'A Symfony API to manage tournaments'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
